name: Update README Last Inventory Run

on:
  workflow_run:
    workflows: ["WIIOMM Inventory & Audit"]
    types:
      - completed

jobs:
  update-readme:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Get latest inventory timestamp
        id: get_time
        run: |
          latest_file=$(ls -t inventory/inventory_*.md | head -n1)
          latest_time=$(echo "$latest_file" | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}_[0-9]{2}-[0-9]{2}-[0-9]{2}')
          latest_time_fmt=$(echo "$latest_time" | sed 's/_/ /; s/-/:/3; s/-/:/2; s/-/:/1')
          echo "LATEST_TIME=$latest_time_fmt" >> $GITHUB_ENV
      - name: Update README
        run: |
          sed -i "s|\*\*Last Inventory Run:\*\* .* <!--LAST_INVENTORY_RUN-->|**Last Inventory Run:** $LATEST_TIME <!--LAST_INVENTORY_RUN-->|" README.md
      - name: Commit and push if changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git diff --cached --quiet || git commit -m "Update last inventory run date in README [skip ci]"
          git push 